### ISSUE TITLE
로그인, 회원가입 버그 수정

### ISSUE THREAD

**Issue by KimKyuHoi** [On-derDog/TadakTadak#109]
### ✨ 기능 리스트

---
- 로그인을 했을때 accesstoken이랑 refreshToken은 제대로 값이 받아오는데 errorToast가 뜸.
- 회원가입이 제대로 안됨.

### ✏ 사용 이유

---

**Comment by DingX2** [comment]
false => null;
true(로그인성공) => "";
이 들어오는 거 확인했습니다.

if (data) 에 동일한 falsy가 들어간거같아요. 둘 다 else 처리된거같네요 

dataNull === null 로 수정하겠습니다.
